#ifndef MPC_H
#define MPC_H

#include <vector>
#include "Eigen-3.3/Eigen/Core"

const size_t N = 25;
using namespace std;

class MPC {
 public:
  MPC();

  virtual ~MPC();

  // Solve the model given an initial state and polynomial coefficients.
  // Return the first actuations.
  vector<double> Solve(Eigen::VectorXd state, Eigen::VectorXd coeffs);

  // Store the predictions generated by the MPC algorithm.
  double mpc_x[N];
  double mpc_y[N];

  double prev_delta;
  double prev_a;
};

#endif /* MPC_H */
